### ISSUE TITLE
review the tags that are allowed. may be add more tags.

### ISSUE THREAD

**Issue by mohitmamoria** [owlgrin/xss#9]

**Comment by rossmb770** [comment]
Currently the <b> tag isn't included here, could I add this and make a merge rerquest?

**Comment by mohitmamoria** [comment]
Yes yes please.

**Comment by rossmb770** [comment]
Actually turns out that the bold tag is defined within the $allowed_html_tags array. However, the tagged version of I am receiving via packagist seems to be an older version. Any chance the newer source could be tagged?

**Comment by mohitmamoria** [comment]
Done. The tag 'v0.1.1' points to the latest version.
- Mohit :)

**Comment by owlgrin** [comment]
The version 0.1.1 is the latest tagged version. You should be good to go now. 👍
